# Numpy
Contains one dimension vector and two dimension matrix

In [1]:
mylist= [1,2,]
mylist

[1, 2]

In [2]:
import numpy as np

In [3]:
np.array(mylist)

array([1, 2])

In [4]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#arange 0 is start digits, 10 is end digits and last 2 is step size from 0 to 10.
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#linspace frist 0 is start digit and 5 is end digits and last 10 is 10 space between digits
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
#identity matrix (eye)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.61547051, 0.20116153, 0.39457545, 0.86011854, 0.56210508])

In [14]:
np.random.rand(5,5)

array([[0.96615406, 0.08916772, 0.52287576, 0.81063785, 0.03211154],
       [0.23352869, 0.72704318, 0.57830944, 0.43367142, 0.86107786],
       [0.67694128, 0.71648316, 0.7625967 , 0.56917108, 0.70093719],
       [0.68163004, 0.22958378, 0.50611725, 0.57896304, 0.73459723],
       [0.72031558, 0.9293529 , 0.1835578 , 0.35259243, 0.66008637]])

In [15]:
np.random.randn(2)

array([-0.33030522, -0.74391274])

In [16]:
np.random.randn(4,4)

array([[-1.18595964, -0.28883597, -0.04899903, -0.64256246],
       [ 0.63128579, -0.45609923, -0.26006753, -0.33111169],
       [ 0.86377792, -0.08665367, -0.3861716 , -0.2829963 ],
       [ 0.80648909,  1.43908388,  0.30329299,  1.16918095]])

In [18]:
np.random.randint(1,100,10)

array([83, 83, 40, 66, 98, 17, 69, 68, 23, 44])

In [30]:
arr = np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr.max()

8

In [33]:
arr.min()

0

In [34]:
#argmaxand argmin is index location
arr.argmax()

8

In [35]:
arr.argmin()

0

In [36]:
arr.shape

(9,)

In [37]:
arr.dtype

dtype('int64')

In [38]:
import numpy.random as ran

In [3]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

# Numpy Indexing and Selection

In [44]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[1]

1

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[1:6:2]

array([1, 3, 5])

In [48]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [50]:
arr[0:5] =100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [52]:
arr_copy =arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr_copy[:]=99
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr_2d = np.array([[5,10,3],[9,4,1],[2,6,7]])
arr_2d

array([[ 5, 10,  3],
       [ 9,  4,  1],
       [ 2,  6,  7]])

In [70]:
arr_2d[0][1]

10

In [68]:
arr_2d[1]

array([9, 4, 1])

In [69]:
arr_2d[2]

array([2, 6, 7])

In [71]:
arr_2d[2][1]

6

In [72]:
arr_2d[2,1]

6

In [74]:
#everything end to col 2 leve col 0
arr_2d[:2,1:]

array([[10,  3],
       [ 4,  1]])

In [75]:
arr_2d[:2]

array([[ 5, 10,  3],
       [ 9,  4,  1]])

In [77]:
arr_2d[1:,:]

array([[9, 4, 1],
       [2, 6, 7]])

Conditional selection

In [78]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
bool_arr=arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [82]:
arr[arr<3]

array([1, 2])

In [6]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [7]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [12]:
arr=np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Numpy Operations
* Array with Array
* Array with scalars
* Universal Array Functions

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
#Array with Array
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [105]:
#array with scalars
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [106]:
arr*30

array([ 30,  60,  90, 120, 150, 180, 210, 240, 270, 300])

In [107]:
1/0

ZeroDivisionError: division by zero

In [108]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [109]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [110]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
#universal array function
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [112]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [113]:
np.max(arr)

10

In [114]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [115]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [14]:
np.random.randn(25)

array([-1.10704691, -0.6286632 , -0.40652924, -0.6054246 ,  0.89870463,
       -0.29261576,  0.20260767,  0.96846704,  1.28356345, -1.18090052,
       -0.5689157 ,  0.26407571,  0.84098162,  0.62550803,  0.64891826,
        0.54509439, -0.56316617, -0.59357914, -2.02754184, -1.93649631,
       -0.1240492 , -0.30962525, -0.87627126, -1.43675885,  1.50571003])

In [35]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [36]:
arr.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
arr*0.01


array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [142]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [155]:
np.sum(mat[:,:1])

55

In [159]:
np.std(mat)

7.211102550927978

In [161]:
arr=np.array([[[1,2,3,],[4,7,6]],[[7,8,9],[6,8,9]]])
arr

array([[[1, 2, 3],
        [4, 7, 6]],

       [[7, 8, 9],
        [6, 8, 9]]])

In [164]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [168]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])